version: '3.7'

services:
  pgdb:
    image: postgres:13-alpine
    env_file:
      - .env.example
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - portaler
  rediscache:
    image: bitnami/redis:6.0
    env_file:
      - .env.example
    ports:
      - '6379:6379'
    networks:
      - portaler
  do_all:
    image: portaler-all:test
    env_file:
      - .env.example
    ports:
      - '8042:80'
    depends_on:
      - pgdb
      - rediscache
    networks:
      - portaler

networks:
  portaler:
    driver: 'bridge'

volumes:
  db_data: {}
