on:
  release:
    types: [published]
jobs:
  copy_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Copy
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.ACCESS_TOKEN }}
          src_path: /.
          dst_path: /.
          src_branch: main
          dst_owner: portaler-zone
          dst_repo_name: portaler-core
          dst_branch: netlify
          clean: true
          exclude: '*/api-server/*'

